#!/usr/bin/env bash

rm -rf ./node_modules

mv /wkarmybuildertemp/node_modules .

rm -r /wkarmybuildertemp

if [ "$#" == 0 ]; then

  npm install
  pushd ./node_modules/materialize-css 
  grunt monitor & 
  popd
  npm start

else
  exec "$@"
fi
