#!/usr/bin/env bash

rm -rf ./node_modules

rm -rf ./src/js

rm -rf ./src/css

rm -rf ./src/fonts

mv /wkarmybuildertemp/node_modules .

mv /wkarmybuildertemp/src/js ./src

mv /wkarmybuildertemp/src/css ./src

mv /wkarmybuildertemp/src/fonts ./src

rm -r /wkarmybuildertemp

if [ "$#" == 0 ]; then

  npm install
  pushd ./node_modules/materialize-css 
  grunt monitor & 
  popd
  npm start

else
  exec "$@"
fi
